### ISSUE TITLE
Support for diesel schema generation with diesel.toml?

### ISSUE THREAD

**Issue by Boscop** [ThinkAlexandria/diesel_geometry#4]
Diesel now uses a `diesel.toml` file that allows configuring the schema generation process:
http://diesel.rs/guides/configuring-diesel-cli/
It also allows adding `use` statements:
```toml
[print_schema]
# Add types from `diesel_full_text_search` like `tsvector`
import_types = ["diesel::sql_types::*", "diesel_full_text_search::types::*"]
```
Would it be possible to support `diesel_geometry` types with automatic schema generation this way?
Or would diesel_cli also have to be aware of the types in this crate (`Point` etc.) in order to generate schemas with such columns?
